---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmc-nginx
  name: cmc-nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: cmc-nginx
  type: LoadBalancer
