---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cmc-nginx-config
data:
  nginx.conf: |
    events {
    }
    http {
      server {
        listen 80;
        server_name cmc-challenge.testenv.site;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://cmc-flask-deployment.default.svc.cluster.local:8000;
        }
      }
      server {
        listen 80;
        server_name grafana.cmc-challenge.testenv.site;

        location / {
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_pass http://cmc-prometheus-grafana.default.svc.cluster.local;
        }
      }
    }
