---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cmc-postgres
  name: cmc-postgres-deployment
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: cmc-postgres
  type: ClusterIP
