---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cmc-postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: cmc-postgres-pvc
  storageClassName: standard
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-standard-cluster-1-pool-1-ccd0eb93-g918
