---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cmc-postgres-pvc
  labels:
    app: cmc-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
